<table>
    <tr><td><?php echo $this->translate('Price');?></td><td><?php echo $this->estate->price; ?></td></tr>
    <tr><td><?php echo $this->translate('Area');?></td><td><?php echo $this->estate->area; ?></td></tr>
    <tr><td><?php echo $this->translate('Rooms');?></td><td><?php echo $this->estate->rooms; ?></td></tr>
    <tr><td><?php echo $this->translate('Floors');?></td><td><?php echo $this->estate->floors; ?></td></tr>
    <tr><td><?php echo $this->translate('Built Year');?></td><td><?php echo $this->estate->year; ?></td></tr>
    <tr><td><?php echo $this->translate('Ground area');?></td><td><?php echo $this->estate->ground; ?></td></tr>
</table>