<h1><?php echo $this->escape($this->item['title']);?></h1>
<?php if ($this->can_edit) {?>
<a href="<?php echo $this->url(array('module' => 'content', 'controller' => 'node', 'action' => 'edit', 'id' => $this->item['id']), 'default', true);?>"><?php echo $this->translate('Edit');?></a>
<?php }?>

<br class="clear" />

<p><?php echo $this->escape($this->item);?></p>

<?php foreach ($this->item->hooks['taxonomy_items'] as $item):
    echo $item;
endforeach;
unset($this->item->hooks['taxonomy_items']);
?>

<?php if($this->item->hooks) {
  foreach ($this->item->hooks as $name => $hook) {
      echo $hook;
  }
}