<?php if (isset($this->item->hooks['gallery_imagecount']) && $this->item->hooks['gallery_imagecount'] > 0) {?>
	<div class="content-item content-<?php echo $this->item['type'];?>-list">
	    <h2>
	        <a href="<?php echo $this->url(array('id' => $this->item['id']), $this->item['type']);?>">
	            <?php echo $this->escape($this->item['title']);?>
	        </a>
	    </h2>
	    <a href="<?php echo $this->url(array('id' => $this->item['id']), $this->item['type']);?>">
	    	<img src="<?php echo $this->item->hooks['gallery_image']; ?>" alt="<?php echo $this->escape($this->item['title']);?>" />
	    </a>
	    <div>
	    	<a href="<?php echo $this->url(array('id' => $this->item['id']), $this->item['type']);?>">
	    		<?php echo $this->item->hooks['gallery_imagecount']." ". $this->translate('images');?>
	    	</a>
	   	</div>
	    <?php
	    unset($this->item->hooks['gallery_image'], $this->item->hooks['gallery_imagecount']);
	    if ($this->item->hooks) {
		    foreach ($this->item->hooks as $hook) {
		        echo $hook;
		    }
	    }
	?>
	</div>
<?php }?>