<a href="<?php echo Zend_Controller_Front::getInstance()->getBaseUrl();?>/" class="home" id="home-link">Home</a>
<a href="/a-brief-overview-of-zoocms" class="home" id="articles-link">ZooCMS</a>
<a href="/bundled-modules" class="home" id="articles-link">Modules</a>
<a href="/zoocms-crew" class="home" id="articles-link">Team</a>
<?php if (Zend_Auth::getInstance()->hasIdentity()) {
  echo '<a href="'.$this->url(array(), 'auth_logout').'">Logout ('.$this->escape(Zend_Auth::getInstance()->getIdentity()->username).')</a>';
}
else {
    echo '<a href="'.$this->url(array(), 'auth_login').'">Login</a>';
}
?>