<?php $estate = $this->item->hooks['estate_node'];?>
    <h2>
        <a href="<?php echo $this->url(array('id' => $this->item['id']), $this->item['type']);?>">
            <?php echo $this->escape($this->item['title']);?>
        </a>
    </h2>
    <table class="result">
        <tr>
          <td>
            <a href="<?php echo $this->url(array('id' => $this->item['id']), $this->item['type']);?>">
                
            </a>
          </td>
          <td class="address">
                <span>
                    <?php echo $this->escape($estate['address']);?><br />
                    <?php echo $this->escape($estate['zipcode'])." ".$this->escape($estate['zipcode']);?>
                </span>
          </td>
          <td>
              <span>
                  <?php echo $this->translate('Price')."<br />".$this->NumberFormat($estate['price']);?>
              </span>
          </td>
          <td><?php echo $this->translate('Monthly')."<br />".$this->escape($estate['monthly']);?></td>
      </tr>
      <tr>
          <td><?php echo $this->translate('Area')."<br />".$this->escape($estate['area']);?></td>
          <td><?php echo $this->translate('Ground area')."<br />".$this->escape($estate['ground']);?></td>
          <td class="rooms"><?php echo $this->translate('Rooms')."<br />".$this->escape($estate['rooms']);?></td>
          <td><?php echo $this->translate('Built Year')."<br />".$this->escape($estate['year']);?></td>
        </tr>
    </table>
    <p><?php echo $this->filter($this->item, 'content', 350); ?></p>
    <?php if($this->item->hooks) {
      foreach ($this->item->hooks as $name => $hook) {
          if ($name != "estate_node") {
              echo $hook;
          }
      }
    }