<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headLink(); ?>
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->themeurl; ?>/css/grid.css" />
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->themeurl; ?>/css/style.css" />
    <?php echo $this->headScript(); ?>
    <?php echo $this->headStyle(); ?>
    <?php echo $this->jQuery(); ?>
  </head>
  <body>
    <?php echo $this->layout()->content; ?>

    <div id="footer"><?php echo $this->footer; ?></div>
    <?php
    if ($this->debug) {
      echo "<div class='debug'>" . $this->debug . '</div>';
    }
    ?>
    <!--
    Page delivered in <?php echo (round((microtime(true) - $_SERVER['REQUEST_TIME']), 4)); ?> seconds
    Page generated in <?php echo (round((microtime(true) - ZfApplication::$_started), 4)); ?> seconds
    -->
  </body>
</html>