<?php 
foreach ( $this->tree as $ele ) {
	if (isset ( $ele ['element'] )) {
		echo $ele ['element'] ['title'] . "";
	}
	if (isset ( $ele ['children'] )) {
		echo "<ul>";
		foreach ( $ele ['children'] as $child ) {
			echo "<li>";
			if (isset ( $child ['element'] )) {
				echo "<a href='#' onclick='selectCategory(".$child['element']['id'].");return false;'>".$child ['element'] ['title']."</a>";
			}
			if (isset ( $child ['children'] )) {
				echo "<ul>";
				foreach ( $child ['children'] as $child2 ) {
					if (is_object ( $child2 ['element'] )) {
						echo "<li>" . $child2 ['element'] ['title'] . "</li>";
					}
				}
				echo "</ul>";
			}
			echo "</li>";
		}
		echo "</ul>";
	}
}