<h1><?php echo $this->category['title'];?></h1>
<?php
$i = 0;
foreach ($this->items as $item) {?>
    <div id="file-<?php echo $item->id;?>" class="content-item filemanager_file_list<?php if (($i % 3) == 0) {echo " clear";} ?>">
    <?php
    if ($item->hooks['filemanager_file']->isImage()):?>
    <p>
        <img src="<?php echo $item->hooks['filemanager_file']->getUrl(130);?>"
                 alt="<?php echo $this->translate('Billede: ').$item['title'];?>" />
    </p>
    <?php else:?>
    <p>
        <img src="<?php echo $this->getTypeImage($item->hooks['filemanager_file']->mimetype);?>"
                 alt="<?php echo $this->translate('Fil: ').$item['title'];?>" />
    </p>
    <?php endif;?>
    <h2>
        <?php echo $this->escape($item['title']);?>
    </h2>
    <p><?php echo $this->filter($item, 'content', 350); ?></p>
    <?php if($item->hooks) {
        foreach ($item->hooks as $name => $hook) {
            if ($name != "filemanager_file") {
                echo $hook;
            }
        }
    }
    ?>
    </div>
<?php
	$i++;
}
?>
<br class="clear" />