<h1><?php echo $this->escape($this->item['title']);?></h1>

<form id="reorderform" action="<?php echo $this->url(array('module' => 'filemanager', 'controller' => 'file', 'action' => 'performReorder', 'id' => $this->item['id']), 'default', true);?>" onsubmit="return false;">
<input type="hidden" name="id" value="<?php echo $this->item['id'];?>" />
<div id="selected-file-list" class="flc-imageReorderer">
<?php
if (isset($this->item->hooks['connected_nodes']) && $this->item->hooks['connected_nodes']) {
    foreach ($this->item->hooks['connected_nodes'] as $image) {
        echo $this->partial("file/sel-item.phtml", array('image' => $image));
    }
}
?>
</div>
</form>
<div id="editDialog" style="display:none;"></div>
